### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by borekb** [ikatyang/prettylint#218] opened 2019-03-12 16:38 UTC
This finishes fine in about 5 seconds:

```
prettier --check \"**/*.{js,jsx,ts,tsx,mdx,json,yaml,yml,css,less,scss,html,graphql,gql}\"
```

This fails with the error after about 30 seconds:

```
prettylint \"**/*.{js,jsx,ts,tsx,mdx,json,yaml,yml,css,less,scss,html,graphql,gql}\"
```

The error is:

```
<--- Last few GCs --->

[13573:0x102801c00]    23323 ms: Scavenge 1392.8 (1422.8) -> 1392.4 (1423.3) MB, 2.8 / 0.0 ms  (average mu = 0.095, current mu = 0.045) allocation failure
[13573:0x102801c00]    23327 ms: Scavenge 1393.1 (1423.3) -> 1392.8 (1424.3) MB, 2.7 / 0.0 ms  (average mu = 0.095, current mu = 0.045) allocation failure
[13573:0x102801c00]    23332 ms: Scavenge 1393.4 (1424.3) -> 1393.1 (1424.8) MB, 2.8 / 0.0 ms  (average mu = 0.095, current mu = 0.045) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x3b908ed5be3d]
    1: StubFrame [pc: 0x3b908ed5d1b0]
Security context: 0x3de4e4c1e6e1 <JSObject>
    2: normalizeString(aka normalizeString) [0x3de47cc6bf21] [path.js:~57] [pc=0x3b908f041dbe](this=0x3de45fc026f1 <undefined>,path=0x3de43e356029 <String[114]: /Users/borekb/dev/redacted/node_modules/webpack/lib/ExportPropertyMainTemplatePlugin.js/>,allowAboveRoot=0x3de45fc029a1 <false>,separat...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003ae75 node::Abort() [/Users/borekb/.nvs/node/10.12.0/x64/bin/node]
 2: 0x10003b07f node::OnFatalError(char const*, char const*) [/Users/borekb/.nvs/node/10.12.0/x64/bin/node]
 3: 0x1001a6a85 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/borekb/.nvs/node/10.12.0/x64/bin/node]
 4: 0x100574422 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/borekb/.nvs/node/10.12.0/x64/bin/node]
 5: 0x100573248 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/borekb/.nvs/node/10.12.0/x64/bin/node]
 6: 0x100570f02 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/borekb/.nvs/node/10.12.0/x64/bin/node]
 7: 0x10057d77c v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/borekb/.nvs/node/10.12.0/x64/bin/node]
 8: 0x10057d7ff v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/borekb/.nvs/node/10.12.0/x64/bin/node]
 9: 0x10054d194 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/borekb/.nvs/node/10.12.0/x64/bin/node]
10: 0x1007d71c0 v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/borekb/.nvs/node/10.12.0/x64/bin/node]
11: 0x3b908ed5be3d
12: 0x3b908ed5d1b0
error Command failed with signal "SIGABRT".
```

**Comment by borekb** [comment] 2019-03-12 16:39
I tried various `--ignore-path` configs as I suspect prettylint is going through my node_modules but nothing helped so far. Note: I've got `.prettierignore` file that looks like this:

```
node_modules
.next
dist
```

**Comment by ikatyang** [comment] 2019-03-13 01:40
This looks like a duplicate of #209, see https://github.com/prettier/prettier/blob/887f800/src/cli/util.js#L403 and https://github.com/ikatyang/prettylint/blob/8dd7b51/src/cli.ts#L55.

**Comment by borekb** [comment] 2019-03-13 08:06
I'm not sure because in #209, adding `node_modules` to my `.prettierignore` (or a file with the `--ignore-path`) helped. This time, I can't get it working.

I've tried creating `.prettierignore` and putting both `node_modules` and `**/node_modules/**` in it, I still get the heap allocation error.

(To be clear, I'm not even sure this is related to node_modules, it's just a guess. Prettier itself has a similar issue in its repo, https://github.com/prettier/prettier/issues/5004, and that one is caused by a large file. However, I'm not aware of any large files in our repo.)

**Comment by ikatyang** [comment] 2019-03-13 08:16
😅 I meant the root cause here seems to be the inconsistent `node_modules` handling between Prettier and prettylint:
- Prettier: always add `!**/node_modules/**` to the glob unless `--with-node-modules` is specified
- prettylint: only add `!**/node_modules/**` to the glob if there is no `.prettierignore`, the `.prettierignore` filtering is happened after the glob, i.e., search everything then do filtering.

Note that the `.prettierignore` filtering in both tools are the same, which should be improved and is tracked in https://github.com/prettier/prettier/issues/4989#issuecomment-414062231.

**Comment by borekb** [comment] 2019-03-13 08:33
> the `.prettierignore` filtering is happened after the glob, i.e., search everything then do filtering

Ah, that's they key point I missed! Is there a workaround for now? prettylint is crashing our build process so I'll take any shortcut there is :)

**Comment by ikatyang** [comment] 2019-03-13 08:42
The only workaround I can think of now is to replace `.prettierignore` with `requirePragma`:

```json
{
  "overrides": [{
    "files": ["glob-you-want-to-ignore"],
    "options": {"requirePragma": true}
  }]
}
```

~~It does not support negative pattern (`!`), though.~~ (Sorry, I misremembered.)

**Closed as completed** 2023-07-27 10:59 UTC
Labels: enhancement
